### ISSUE TITLE
Status Topic

### ISSUE THREAD

**Issue by tySwift93** [stjohnjohnson/smartthings-mqtt-bridge#25]
I have been using this and it is incredible!  Thank you very much for putting this together for us SmartThings users who like to make our own interfaces in Home Assistant.

Would it be possible to include a separate state topic for each exposed ST device?

For example, we currently get events AND send commands to smartthings/Fireplace Lights/switch.
I'd like to be able to get events at smartthings/Fireplace Lights/switch/state and send commands to smartthings/Fireplace Lights/switch/cmd.  That way when I send a command, I can confirm that it worked by checking the state again.

Looking forward to your response!

**Comment by stjohnjohnson** [comment]
Howdy!  Glad you like our project!

I don't see why we couldn't add this feature, it should be pretty straight forward.  What do you think the config.yaml should look like?

**Comment by tySwift93** [comment]
Here's an example, based on what mine would look like with this implemented:
```yaml
mqtt:
    host: 192.168.1.xx
    preface: smartthings
    state_suffix: state
    command_suffix: cmd
    username: xxxxxxx
    password: xxxxxxx

port: xxxx
```
In Home Assistant, an example MQTT switch could now look like this:
```yaml
switch:
  platform: mqtt
  name: "Fireplace Lights"
  state_topic: "smartthings/Fireplace Lights/switch/state"
  command_topic: "smartthings/Fireplace Lights/switch/cmd"
  payload_on: "on"
  payload_off: "off"
  optimistic: false  #False because we can now get a state confirmation from SmartThings!
  qos: 0
```

What do you think?
