### ISSUE TITLE
MQTT Bridge issues

### ISSUE THREAD

**Issue by rdrivas123** [stjohnjohnson/smartthings-mqtt-bridge#36]
Hello,

I am not sure that my issues is with the MQTT, it seems to be running, but how do I tell it is communicating to my hub?

**Comment by stjohnjohnson** [comment]
I would take a look at two logs:
 - MQTT Bridge event.log
 - SmartThings Live Logger: https://graph.api.smartthings.com/ide/logs

**Comment by rdrivas123** [comment]
I see nothing in the Live logger at all, where would the MQTT log be located?

**Comment by rdrivas123** [comment]
OK, I now see things logging and coming to and from the hub, but I cant control my lights or see anything working.
I suspect it is because I have the wrong info in my configuration.yaml

Light:
  Platform: mqtt
  Name: “Kitchen Bar 1”
  state_topic: “smartthings/Kitchen Bar 1/switch”
  command_topic: “smartthings/Kitchen Bar 1/switch”

How do I identify my devices in home assistant now that the MQTT seems to be pushing data around?

**Comment by stjohnjohnson** [comment]
This is an example of my config:
```yaml
light:
  - platform: mqtt
    name: "Backyard Lights"
    state_topic: "smartthings/Backyard Lights/switch"
    command_topic: "smartthings/Backyard Lights/switch"
    payload_on: "on"
    payload_off: "off"
    optimistic: true
```
