### ISSUE TITLE
MQTT Garage Door Issues

### ISSUE THREAD

**Issue by creamcheesehero** [stjohnjohnson/smartthings-mqtt-bridge#38]
I am able to create a Garage Door component and successfully open the door and keep track of its open/closed state. However, I am not able to shut the door from Home Assistant. Here's the yaml in question. Any advice would be greatly appreciated.

```
garage_door:
  - platform: mqtt
    name: 'Garage Door'
    state_topic: 'smartthings/Garage Door/door'
    command_topic: 'smartthings/Garage Door/door'  
    optimistic: false
    qos: 0
    retain: true
    state_open: 'STATE_OPEN'
    state_closed: 'STATE_CLOSED'
    service_open: 'SERVICE_OPEN'
    service_close: 'SERVICE_CLOSE'
```

**Comment by chilicheech** [comment]
Here's what worked for me:
```
garage_door:
  platform: mqtt
  name: Garage Door
  state_topic: "smartthings/Garage Door Opener/contact"
  command_topic: "smartthings/Garage Door Opener/door"
  state_open: 'open'
  state_closed: 'closed'
  service_open: 'open'
  service_close: 'closed'
  retain: true
```

**Comment by stjohnjohnson** [comment]
@chilicheech is right, the smartapp looks for certain payloads:
https://github.com/stjohnjohnson/smartthings-mqtt-bridge/blob/master/smartapps/stj/mqtt-bridge.src/mqtt-bridge.groovy#L590-L596

**Comment by creamcheesehero** [comment]
@stjohnjohnson last night when trying this I had the same payloads as the config @chilicheech provided and encountered the same issue, so I reverted to the defaults from HA. The major difference between this config and mine is that my state topic was door and not contact. After updating my state topic to contact and reverting back to the payloads from the example above I encountered the same issue. I changed the optimistic property to true and that seems to have done the trick in combination with the update to the state top and payloads. I am using a GoControl/Linear GD00Z-4 Garage door opener in case this information is of value to anyone else. Here is my updated and functional config.

```
garage_door:
  platform: mqtt
  name: 'Garage Door'
  state_topic: 'smartthings/Garage Door/contact'
  command_topic: 'smartthings/Garage Door/door'  
  state_open: 'open'
  state_closed: 'closed'
  service_open: 'open'
  service_close: 'closed'
  retain: true
  optimistic: true
```
