### ISSUE TITLE
Not seeing commands from SmartThings. 

### ISSUE THREAD

**Issue by rsissons** [stjohnjohnson/smartthings-mqtt-bridge#69]
I have HA setup and my devices are listed. I have 2 OSRM bulbs I can control using Smartthings and also Google Home + IFTTT. 

I got the smarthings-mqtt-bridge running on my HA pi3. 
Sub to it using:
mosquitto_sub -d -u pi -P xxxxx -t smartthings/#
 and have the code:
```
switch:
  platform: mqtt
  name: "RonsLivingRoomLamp"
  state_topic: "smartthings/RonsLivingRoomLamp/switch"
  command_topic: "smartthings/RonsLivingRoomLamp/switch"
  brightness_state_topic: "smartthings/RonsLivingRoomLamp/level"
  brightness_command_topic: "smartthings/RonsLivingRoomLamp/level"
  payload_on: "on"
  payload_off: "off"
  retain: true
```  

When I click the switch on the HA, I see the messages in MQTT

Client mosqsub/13417-roosterpi received PUBLISH (d0, q0, r0, m0, 'smartthings/RonsLivingRoomLamp/switch', ... (2 bytes))
on
Client mosqsub/13417-roosterpi received PUBLISH (d0, q0, r0, m0, 'smartthings/RonsLivingRoomLamp/switch', ... (3 bytes))
off

In Smarthings IDE, I setup the MQTT Bridge Device Handler and setup the device per the instructions. for the IP address in the preferences, do I put the local internal address to the HA server running the MQTT bridge, or an external(duckdns)? I have tried both ways and when I turn the bulb on using the HA Switch, I see the command in the MQTT, but it doesn't do anything to the lamp. I also don't see anything the reverse way whten I trigger the bulb using the smartthings app on my phone. I don't see it. 

It's like Smartthings and the MQTT are not connected somehow.

Am I missing something?
