### ISSUE TITLE
Getting this working as a addon for the new hassio homeassistant

### ISSUE THREAD

**Issue by CTLS** [stjohnjohnson/smartthings-mqtt-bridge#83]
I think once hass.io becomes more finalized, this will make setup of smartthings-mqtt-bridge on home assistant a lot easier.  Hassio runs all addons in docker files and allows setup of the addons through the frontend.
There is some more info on how to set up hassio addons at- https://home-assistant.io/hassio/addon_config/

**Comment by rogersmj** [comment]
100% agree! I just started playing with Hass.io and I love it, everything's so plug and play...but I can't use it yet because I completely depend on this great SmartThings MQTT bridge.

I have pretty much zero experience with docker, but if no one tackles this in the next few weeks I may try to make some time to hack away at it.

**Comment by rogersmj** [comment]
FYI @CTLS this was just posted: https://github.com/vkorn/hassio-addons/tree/master/smartthings

**Comment by AJax2012** [comment]
@rogersmj have you gotten this working? I'm working with it and can't figure out how to connect it to SmartThings API...

**Comment by mth3r** [comment]
I'm looking for help too.  Just a description of what each configuration item is would be helpful...something to the effect that the MQTT host Ip is the raspberrypi ip.  I think it is pretty simple, but I'm obviously missing something

**Comment by Darksabre** [comment]
Definitely would like to get this working.  I tried pasting the repo link into HASSIO, but it doesnt seem to do anything.  Any help would be great!

**Comment by jamescw** [comment]
I got this working and it's a great solution for running the whole stack on an Rpi 3!

Firstly the addon linked above was missing a small piece of config that allows the addon to expose the port of the smartthings-bridge server. I created a small patch and submitted to the authors repo, hopefully that will get merged soon: https://github.com/vkorn/hassio-addons/pull/12

Then I used the following steps:

1. I installed the hass.io Mosquitto broker addon with all the default settings.
2. Installed the SmartThings addon with all the default settings but set the username and password fields to empty strings as the default config for the Mosquitto broker does not set these.
3. Then followed all the steps here to connect SmartThings to Hass.io: https://github.com/stjohnjohnson/smartthings-mqtt-bridge#usage

Add the following config to Hass:
```
mqtt:
  broker: localhost
  port: 1883
  client_id: hassio
  keepalive: 60
```

Then define a light or sensor etc:
```
light:
  platform: mqtt
  name: "Lamp"
  state_topic: "smartthings/Lamp/switch/state"
  command_topic: "smartthings/Lamp/switch/cmd"
  payload_on: "on"
  payload_off: "off"

sensor:
  - platform: mqtt
    state_topic: "smartthings/Motion Sensor/temperature/state"
```
